#!/bin/sh -x

inc_flags="`pkg-config --cflags osss-ucx`"

tmpsrc="pull.c"

echo '#include <shmem.h>' > $tmpsrc

caveat=<<EOT
EOT

bindgen                                           \
    --no-doc-comments                             \
    --enable-function-attribute-detection         \
    --whitelist-var '^SHMEM_.*'                   \
    --whitelist-var '^_SHMEM_.*'                  \
    --whitelist-function '^sh.*'                  \
    $tmpsrc                                       \
    --raw-line '#![allow(non_camel_case_types,improper_ctypes)] // not our fault' \
    -o shmemlib/src/lib.rs                        \
    --                                            \
    $inc_flags

rm -f $tmpsrc
