#!/bin/sh -x

INC_FLAGS="`pkg-config --cflags osss-ucx`"

TMPSRC="pull.c"

echo '#include <shmem.h>' > $TMPSRC

bindgen \
    --no-doc-comments \
    --enable-function-attribute-detection \
    --whitelist-var '^SHMEM_.*' \
    --whitelist-var '^_SHMEM_.*' \
    --whitelist-function '^sh.*' \
    $TMPSRC \
    -o shmemlib/src/lib.rs \
    -- \
    $INC_FLAGS

rm -f $TMPSRC
