
[package]
name = "hashtest"
version = "0.1.0"
authors = ["Tony Curtis <anthony.curtis@stonybrook.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shmem = { path = "../shmem" }
state = "0.5"
libc = "0.2"
